// <copyright file="AuditArrayElements.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// AuditArrayElements.
    /// </summary>
    public class AuditArrayElements
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuditArrayElements"/> class.
        /// </summary>
        public AuditArrayElements()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuditArrayElements"/> class.
        /// </summary>
        /// <param name="audits">Audits.</param>
        public AuditArrayElements(
            List<Models.AuditResponseAuditsItems> audits = null)
        {
            this.Audits = audits;
        }

        /// <summary>
        /// Gets or sets Audits.
        /// </summary>
        [JsonProperty("Audits", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.AuditResponseAuditsItems> Audits { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AuditArrayElements : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AuditArrayElements other &&
                (this.Audits == null && other.Audits == null ||
                 this.Audits?.Equals(other.Audits) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Audits = {(this.Audits == null ? "null" : $"[{string.Join(", ", this.Audits)} ]")}");
        }
    }
}