// <copyright file="CardUsageSummaryResponse.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// CardUsageSummaryResponse.
    /// </summary>
    public class CardUsageSummaryResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CardUsageSummaryResponse"/> class.
        /// </summary>
        public CardUsageSummaryResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CardUsageSummaryResponse"/> class.
        /// </summary>
        /// <param name="usageSummary">UsageSummary.</param>
        public CardUsageSummaryResponse(
            List<Models.UsageSummary> usageSummary = null)
        {
            this.UsageSummary = usageSummary;
        }

        /// <summary>
        /// Gets or sets UsageSummary.
        /// </summary>
        [JsonProperty("UsageSummary", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.UsageSummary> UsageSummary { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CardUsageSummaryResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CardUsageSummaryResponse other &&
                (this.UsageSummary == null && other.UsageSummary == null ||
                 this.UsageSummary?.Equals(other.UsageSummary) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"UsageSummary = {(this.UsageSummary == null ? "null" : $"[{string.Join(", ", this.UsageSummary)} ]")}");
        }
    }
}