// <copyright file="CardTypeResponseCustomerCardTypesItems.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// CardTypeResponseCustomerCardTypesItems.
    /// </summary>
    public class CardTypeResponseCustomerCardTypesItems
    {
        private bool? isCardAvailableForDownload;
        private bool? eMVContactless;
        private bool? rFID;
        private bool? pINChangeSupported;
        private bool? requirePIN;
        private bool? offlinePIN;
        private List<Models.PurchaseCategories> purchaseCategories;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "IsCardAvailableForDownload", false },
            { "EMVContactless", false },
            { "RFID", false },
            { "PINChangeSupported", false },
            { "RequirePIN", false },
            { "OfflinePIN", false },
            { "PurchaseCategories", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="CardTypeResponseCustomerCardTypesItems"/> class.
        /// </summary>
        public CardTypeResponseCustomerCardTypesItems()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CardTypeResponseCustomerCardTypesItems"/> class.
        /// </summary>
        /// <param name="cardTypeId">CardTypeId.</param>
        /// <param name="tokenTypeId">TokenTypeId.</param>
        /// <param name="cardTypeName">CardTypeName.</param>
        /// <param name="tokenTypeName">TokenTypeName.</param>
        /// <param name="pANLength">PANLength.</param>
        /// <param name="expiryPeriod">ExpiryPeriod.</param>
        /// <param name="isNational">IsNational.</param>
        /// <param name="isInternational">IsInternational.</param>
        /// <param name="isCRT">IsCRT.</param>
        /// <param name="isFleet">IsFleet.</param>
        /// <param name="isShellSitesOnly">IsShellSitesOnly.</param>
        /// <param name="isPartnerSitesIncluded">IsPartnerSitesIncluded.</param>
        /// <param name="canHavePIN">CanHavePIN.</param>
        /// <param name="isVirtual">IsVirtual.</param>
        /// <param name="isActive">IsActive.</param>
        /// <param name="isCardAvailableForDownload">IsCardAvailableForDownload.</param>
        /// <param name="colCoCurrencyCode">ColCoCurrencyCode.</param>
        /// <param name="colCoCurrencySymbol">ColCoCurrencySymbol.</param>
        /// <param name="eMVContactless">EMVContactless.</param>
        /// <param name="rFID">RFID.</param>
        /// <param name="pINChangeSupported">PINChangeSupported.</param>
        /// <param name="requirePIN">RequirePIN.</param>
        /// <param name="offlinePIN">OfflinePIN.</param>
        /// <param name="mediumTypeID">MediumTypeID.</param>
        /// <param name="mediumType">MediumType.</param>
        /// <param name="cartTypeAccounts">CartTypeAccounts.</param>
        /// <param name="purchaseCategories">PurchaseCategories.</param>
        public CardTypeResponseCustomerCardTypesItems(
            int? cardTypeId = null,
            int? tokenTypeId = null,
            string cardTypeName = null,
            string tokenTypeName = null,
            int? pANLength = null,
            int? expiryPeriod = null,
            bool? isNational = null,
            bool? isInternational = null,
            bool? isCRT = null,
            bool? isFleet = null,
            bool? isShellSitesOnly = null,
            bool? isPartnerSitesIncluded = null,
            bool? canHavePIN = null,
            bool? isVirtual = null,
            bool? isActive = null,
            bool? isCardAvailableForDownload = null,
            string colCoCurrencyCode = null,
            string colCoCurrencySymbol = null,
            bool? eMVContactless = null,
            bool? rFID = null,
            bool? pINChangeSupported = null,
            bool? requirePIN = null,
            bool? offlinePIN = null,
            int? mediumTypeID = null,
            string mediumType = null,
            List<Models.CartTypeAccount> cartTypeAccounts = null,
            List<Models.PurchaseCategories> purchaseCategories = null)
        {
            this.CardTypeId = cardTypeId;
            this.TokenTypeId = tokenTypeId;
            this.CardTypeName = cardTypeName;
            this.TokenTypeName = tokenTypeName;
            this.PANLength = pANLength;
            this.ExpiryPeriod = expiryPeriod;
            this.IsNational = isNational;
            this.IsInternational = isInternational;
            this.IsCRT = isCRT;
            this.IsFleet = isFleet;
            this.IsShellSitesOnly = isShellSitesOnly;
            this.IsPartnerSitesIncluded = isPartnerSitesIncluded;
            this.CanHavePIN = canHavePIN;
            this.IsVirtual = isVirtual;
            this.IsActive = isActive;

            if (isCardAvailableForDownload != null)
            {
                this.IsCardAvailableForDownload = isCardAvailableForDownload;
            }
            this.ColCoCurrencyCode = colCoCurrencyCode;
            this.ColCoCurrencySymbol = colCoCurrencySymbol;

            if (eMVContactless != null)
            {
                this.EMVContactless = eMVContactless;
            }

            if (rFID != null)
            {
                this.RFID = rFID;
            }

            if (pINChangeSupported != null)
            {
                this.PINChangeSupported = pINChangeSupported;
            }

            if (requirePIN != null)
            {
                this.RequirePIN = requirePIN;
            }

            if (offlinePIN != null)
            {
                this.OfflinePIN = offlinePIN;
            }
            this.MediumTypeID = mediumTypeID;
            this.MediumType = mediumType;
            this.CartTypeAccounts = cartTypeAccounts;

            if (purchaseCategories != null)
            {
                this.PurchaseCategories = purchaseCategories;
            }
        }

        /// <summary>
        /// Card Type Id in Cards Platform.
        /// </summary>
        [JsonProperty("CardTypeId", NullValueHandling = NullValueHandling.Ignore)]
        public int? CardTypeId { get; set; }

        /// <summary>
        /// Token type identifier.
        /// </summary>
        [JsonProperty("TokenTypeId", NullValueHandling = NullValueHandling.Ignore)]
        public int? TokenTypeId { get; set; }

        /// <summary>
        /// Card Type Name.
        /// </summary>
        [JsonProperty("CardTypeName", NullValueHandling = NullValueHandling.Ignore)]
        public string CardTypeName { get; set; }

        /// <summary>
        /// Token Type Name.
        /// </summary>
        [JsonProperty("TokenTypeName", NullValueHandling = NullValueHandling.Ignore)]
        public string TokenTypeName { get; set; }

        /// <summary>
        /// PAN Length.
        /// </summary>
        [JsonProperty("PANLength", NullValueHandling = NullValueHandling.Ignore)]
        public int? PANLength { get; set; }

        /// <summary>
        /// Default Expiry period.
        /// </summary>
        [JsonProperty("ExpiryPeriod", NullValueHandling = NullValueHandling.Ignore)]
        public int? ExpiryPeriod { get; set; }

        /// <summary>
        /// True/False – Whether it is a National Card type or not.
        /// </summary>
        [JsonProperty("IsNational", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsNational { get; set; }

        /// <summary>
        /// True/False – Whether it is an International Card type or not.
        /// </summary>
        [JsonProperty("IsInternational", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsInternational { get; set; }

        /// <summary>
        /// True/False – Wether it is a CRT Card type or not.
        /// </summary>
        [JsonProperty("IsCRT", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsCRT { get; set; }

        /// <summary>
        /// True/False – Whether it is it a Fleet Card typeor not.
        /// </summary>
        [JsonProperty("IsFleet", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsFleet { get; set; }

        /// <summary>
        /// True/False – Whether it is only allowed in Shell Stations or not.
        /// </summary>
        [JsonProperty("IsShellSitesOnly", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsShellSitesOnly { get; set; }

        /// <summary>
        /// True/False – Whether this card type is allowed in partner Stations.
        /// </summary>
        [JsonProperty("IsPartnerSitesIncluded", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsPartnerSitesIncluded { get; set; }

        /// <summary>
        /// True/False – Whether the cards of this card type can have PIN.
        /// </summary>
        [JsonProperty("CanHavePIN", NullValueHandling = NullValueHandling.Ignore)]
        public bool? CanHavePIN { get; set; }

        /// <summary>
        /// True/False - Whether it is a Virtual Card type or not.
        /// </summary>
        [JsonProperty("IsVirtual", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsVirtual { get; set; }

        /// <summary>
        /// Whether card type is active or not.
        /// </summary>
        [JsonProperty("IsActive", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsActive { get; set; }

        /// <summary>
        /// Whether card type is available for download.
        /// </summary>
        [JsonProperty("IsCardAvailableForDownload")]
        public bool? IsCardAvailableForDownload
        {
            get
            {
                return this.isCardAvailableForDownload;
            }

            set
            {
                this.shouldSerialize["IsCardAvailableForDownload"] = true;
                this.isCardAvailableForDownload = value;
            }
        }

        /// <summary>
        /// ISO currency code of the country.
        /// </summary>
        [JsonProperty("ColCoCurrencyCode", NullValueHandling = NullValueHandling.Ignore)]
        public string ColCoCurrencyCode { get; set; }

        /// <summary>
        /// Currency symbol of the country.
        /// </summary>
        [JsonProperty("ColCoCurrencySymbol", NullValueHandling = NullValueHandling.Ignore)]
        public string ColCoCurrencySymbol { get; set; }

        /// <summary>
        /// Is Europay, MasterCard, and Visa Contactless enabled or not.
        /// </summary>
        [JsonProperty("EMVContactless")]
        public bool? EMVContactless
        {
            get
            {
                return this.eMVContactless;
            }

            set
            {
                this.shouldSerialize["EMVContactless"] = true;
                this.eMVContactless = value;
            }
        }

        /// <summary>
        /// Whether the card type is enabled for RFID (Radio Frequency Identification)
        /// </summary>
        [JsonProperty("RFID")]
        public bool? RFID
        {
            get
            {
                return this.rFID;
            }

            set
            {
                this.shouldSerialize["RFID"] = true;
                this.rFID = value;
            }
        }

        /// <summary>
        /// PIN change supported or not.
        /// </summary>
        [JsonProperty("PINChangeSupported")]
        public bool? PINChangeSupported
        {
            get
            {
                return this.pINChangeSupported;
            }

            set
            {
                this.shouldSerialize["PINChangeSupported"] = true;
                this.pINChangeSupported = value;
            }
        }

        /// <summary>
        /// Whether a PIN is mandatory for the cards of this card type.
        /// </summary>
        [JsonProperty("RequirePIN")]
        public bool? RequirePIN
        {
            get
            {
                return this.requirePIN;
            }

            set
            {
                this.shouldSerialize["RequirePIN"] = true;
                this.requirePIN = value;
            }
        }

        /// <summary>
        /// Whether offline PIN is enabled or not.
        /// </summary>
        [JsonProperty("OfflinePIN")]
        public bool? OfflinePIN
        {
            get
            {
                return this.offlinePIN;
            }

            set
            {
                this.shouldSerialize["OfflinePIN"] = true;
                this.offlinePIN = value;
            }
        }

        /// <summary>
        /// <![CDATA[
        /// Id of the medium type identifier. <br><br> Full list below - <br> 1 - Fuel Card <br> 2 - Fuel Card with EV <br> 3 - EV only  <br> 4 - Fuel Card and Key Fob <br> 5 - Key Fob <br> 6 - Virtual Card <br> 7 - NPII Token <br> 8 – Smartpay Token
        /// ]]>
        /// </summary>
        [JsonProperty("MediumTypeID", NullValueHandling = NullValueHandling.Ignore)]
        public int? MediumTypeID { get; set; }

        /// <summary>
        /// <![CDATA[
        /// Name of the medium type identifier. <br><br> Full list below - <br> 1 - Fuel Card <br> 2 - Fuel Card with EV <br> 3 - EV only  <br> 4 - Fuel Card and Key Fob <br> 5 - Key Fob <br> 6 - Virtual Card <br> 7 - NPII Token <br> 8 – Smartpay Token
        /// ]]>
        /// </summary>
        [JsonProperty("MediumType", NullValueHandling = NullValueHandling.Ignore)]
        public string MediumType { get; set; }

        /// <summary>
        /// List of accounts.
        /// </summary>
        [JsonProperty("CartTypeAccounts", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.CartTypeAccount> CartTypeAccounts { get; set; }

        /// <summary>
        /// Gets or sets PurchaseCategories.
        /// </summary>
        [JsonProperty("PurchaseCategories")]
        public List<Models.PurchaseCategories> PurchaseCategories
        {
            get
            {
                return this.purchaseCategories;
            }

            set
            {
                this.shouldSerialize["PurchaseCategories"] = true;
                this.purchaseCategories = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CardTypeResponseCustomerCardTypesItems : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetIsCardAvailableForDownload()
        {
            this.shouldSerialize["IsCardAvailableForDownload"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetEMVContactless()
        {
            this.shouldSerialize["EMVContactless"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetRFID()
        {
            this.shouldSerialize["RFID"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPINChangeSupported()
        {
            this.shouldSerialize["PINChangeSupported"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetRequirePIN()
        {
            this.shouldSerialize["RequirePIN"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetOfflinePIN()
        {
            this.shouldSerialize["OfflinePIN"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPurchaseCategories()
        {
            this.shouldSerialize["PurchaseCategories"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeIsCardAvailableForDownload()
        {
            return this.shouldSerialize["IsCardAvailableForDownload"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeEMVContactless()
        {
            return this.shouldSerialize["EMVContactless"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeRFID()
        {
            return this.shouldSerialize["RFID"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePINChangeSupported()
        {
            return this.shouldSerialize["PINChangeSupported"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeRequirePIN()
        {
            return this.shouldSerialize["RequirePIN"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeOfflinePIN()
        {
            return this.shouldSerialize["OfflinePIN"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePurchaseCategories()
        {
            return this.shouldSerialize["PurchaseCategories"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CardTypeResponseCustomerCardTypesItems other &&
                (this.CardTypeId == null && other.CardTypeId == null ||
                 this.CardTypeId?.Equals(other.CardTypeId) == true) &&
                (this.TokenTypeId == null && other.TokenTypeId == null ||
                 this.TokenTypeId?.Equals(other.TokenTypeId) == true) &&
                (this.CardTypeName == null && other.CardTypeName == null ||
                 this.CardTypeName?.Equals(other.CardTypeName) == true) &&
                (this.TokenTypeName == null && other.TokenTypeName == null ||
                 this.TokenTypeName?.Equals(other.TokenTypeName) == true) &&
                (this.PANLength == null && other.PANLength == null ||
                 this.PANLength?.Equals(other.PANLength) == true) &&
                (this.ExpiryPeriod == null && other.ExpiryPeriod == null ||
                 this.ExpiryPeriod?.Equals(other.ExpiryPeriod) == true) &&
                (this.IsNational == null && other.IsNational == null ||
                 this.IsNational?.Equals(other.IsNational) == true) &&
                (this.IsInternational == null && other.IsInternational == null ||
                 this.IsInternational?.Equals(other.IsInternational) == true) &&
                (this.IsCRT == null && other.IsCRT == null ||
                 this.IsCRT?.Equals(other.IsCRT) == true) &&
                (this.IsFleet == null && other.IsFleet == null ||
                 this.IsFleet?.Equals(other.IsFleet) == true) &&
                (this.IsShellSitesOnly == null && other.IsShellSitesOnly == null ||
                 this.IsShellSitesOnly?.Equals(other.IsShellSitesOnly) == true) &&
                (this.IsPartnerSitesIncluded == null && other.IsPartnerSitesIncluded == null ||
                 this.IsPartnerSitesIncluded?.Equals(other.IsPartnerSitesIncluded) == true) &&
                (this.CanHavePIN == null && other.CanHavePIN == null ||
                 this.CanHavePIN?.Equals(other.CanHavePIN) == true) &&
                (this.IsVirtual == null && other.IsVirtual == null ||
                 this.IsVirtual?.Equals(other.IsVirtual) == true) &&
                (this.IsActive == null && other.IsActive == null ||
                 this.IsActive?.Equals(other.IsActive) == true) &&
                (this.IsCardAvailableForDownload == null && other.IsCardAvailableForDownload == null ||
                 this.IsCardAvailableForDownload?.Equals(other.IsCardAvailableForDownload) == true) &&
                (this.ColCoCurrencyCode == null && other.ColCoCurrencyCode == null ||
                 this.ColCoCurrencyCode?.Equals(other.ColCoCurrencyCode) == true) &&
                (this.ColCoCurrencySymbol == null && other.ColCoCurrencySymbol == null ||
                 this.ColCoCurrencySymbol?.Equals(other.ColCoCurrencySymbol) == true) &&
                (this.EMVContactless == null && other.EMVContactless == null ||
                 this.EMVContactless?.Equals(other.EMVContactless) == true) &&
                (this.RFID == null && other.RFID == null ||
                 this.RFID?.Equals(other.RFID) == true) &&
                (this.PINChangeSupported == null && other.PINChangeSupported == null ||
                 this.PINChangeSupported?.Equals(other.PINChangeSupported) == true) &&
                (this.RequirePIN == null && other.RequirePIN == null ||
                 this.RequirePIN?.Equals(other.RequirePIN) == true) &&
                (this.OfflinePIN == null && other.OfflinePIN == null ||
                 this.OfflinePIN?.Equals(other.OfflinePIN) == true) &&
                (this.MediumTypeID == null && other.MediumTypeID == null ||
                 this.MediumTypeID?.Equals(other.MediumTypeID) == true) &&
                (this.MediumType == null && other.MediumType == null ||
                 this.MediumType?.Equals(other.MediumType) == true) &&
                (this.CartTypeAccounts == null && other.CartTypeAccounts == null ||
                 this.CartTypeAccounts?.Equals(other.CartTypeAccounts) == true) &&
                (this.PurchaseCategories == null && other.PurchaseCategories == null ||
                 this.PurchaseCategories?.Equals(other.PurchaseCategories) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CardTypeId = {(this.CardTypeId == null ? "null" : this.CardTypeId.ToString())}");
            toStringOutput.Add($"TokenTypeId = {(this.TokenTypeId == null ? "null" : this.TokenTypeId.ToString())}");
            toStringOutput.Add($"CardTypeName = {this.CardTypeName ?? "null"}");
            toStringOutput.Add($"TokenTypeName = {this.TokenTypeName ?? "null"}");
            toStringOutput.Add($"PANLength = {(this.PANLength == null ? "null" : this.PANLength.ToString())}");
            toStringOutput.Add($"ExpiryPeriod = {(this.ExpiryPeriod == null ? "null" : this.ExpiryPeriod.ToString())}");
            toStringOutput.Add($"IsNational = {(this.IsNational == null ? "null" : this.IsNational.ToString())}");
            toStringOutput.Add($"IsInternational = {(this.IsInternational == null ? "null" : this.IsInternational.ToString())}");
            toStringOutput.Add($"IsCRT = {(this.IsCRT == null ? "null" : this.IsCRT.ToString())}");
            toStringOutput.Add($"IsFleet = {(this.IsFleet == null ? "null" : this.IsFleet.ToString())}");
            toStringOutput.Add($"IsShellSitesOnly = {(this.IsShellSitesOnly == null ? "null" : this.IsShellSitesOnly.ToString())}");
            toStringOutput.Add($"IsPartnerSitesIncluded = {(this.IsPartnerSitesIncluded == null ? "null" : this.IsPartnerSitesIncluded.ToString())}");
            toStringOutput.Add($"CanHavePIN = {(this.CanHavePIN == null ? "null" : this.CanHavePIN.ToString())}");
            toStringOutput.Add($"IsVirtual = {(this.IsVirtual == null ? "null" : this.IsVirtual.ToString())}");
            toStringOutput.Add($"IsActive = {(this.IsActive == null ? "null" : this.IsActive.ToString())}");
            toStringOutput.Add($"IsCardAvailableForDownload = {(this.IsCardAvailableForDownload == null ? "null" : this.IsCardAvailableForDownload.ToString())}");
            toStringOutput.Add($"ColCoCurrencyCode = {this.ColCoCurrencyCode ?? "null"}");
            toStringOutput.Add($"ColCoCurrencySymbol = {this.ColCoCurrencySymbol ?? "null"}");
            toStringOutput.Add($"EMVContactless = {(this.EMVContactless == null ? "null" : this.EMVContactless.ToString())}");
            toStringOutput.Add($"RFID = {(this.RFID == null ? "null" : this.RFID.ToString())}");
            toStringOutput.Add($"PINChangeSupported = {(this.PINChangeSupported == null ? "null" : this.PINChangeSupported.ToString())}");
            toStringOutput.Add($"RequirePIN = {(this.RequirePIN == null ? "null" : this.RequirePIN.ToString())}");
            toStringOutput.Add($"OfflinePIN = {(this.OfflinePIN == null ? "null" : this.OfflinePIN.ToString())}");
            toStringOutput.Add($"MediumTypeID = {(this.MediumTypeID == null ? "null" : this.MediumTypeID.ToString())}");
            toStringOutput.Add($"MediumType = {this.MediumType ?? "null"}");
            toStringOutput.Add($"CartTypeAccounts = {(this.CartTypeAccounts == null ? "null" : $"[{string.Join(", ", this.CartTypeAccounts)} ]")}");
            toStringOutput.Add($"PurchaseCategories = {(this.PurchaseCategories == null ? "null" : $"[{string.Join(", ", this.PurchaseCategories)} ]")}");
        }
    }
}