// <copyright file="CardGroupReq.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// CardGroupReq.
    /// </summary>
    public class CardGroupReq
    {
        private int? page;
        private int? pageSize;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "Page", true },
            { "PageSize", true },
        };

        private Dictionary<string, bool> hasPropertySetterCalledFor = new Dictionary<string, bool>
        {
            { "Page", false },
            { "PageSize", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="CardGroupReq"/> class.
        /// </summary>
        public CardGroupReq()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CardGroupReq"/> class.
        /// </summary>
        /// <param name="filters">Filters.</param>
        /// <param name="page">Page.</param>
        /// <param name="pageSize">PageSize.</param>
        public CardGroupReq(
            Models.CardGroupRequest filters = null,
            int? page = 1,
            int? pageSize = 50)
        {
            this.Filters = filters;
            this.Page = page;
            this.PageSize = pageSize;
        }

        /// <summary>
        /// Gets or sets Filters.
        /// </summary>
        [JsonProperty("Filters", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CardGroupRequest Filters { get; set; }

        /// <summary>
        /// Page Number (as shown to the users)
        /// </summary>
        [JsonProperty("Page")]
        public int? Page
        {
            get
            {
                if (!hasPropertySetterCalledFor["Page"] &&
                    page == null)
                {
                    return 1; // Default value
                }

                return this.page;
            }

            set
            {
                this.shouldSerialize["Page"] = true;
                hasPropertySetterCalledFor["Page"] = true;
                this.page = value;
            }
        }

        /// <summary>
        /// Page Size – Number of records to show on a page.
        /// </summary>
        [JsonProperty("PageSize")]
        public int? PageSize
        {
            get
            {
                if (!hasPropertySetterCalledFor["PageSize"] &&
                    pageSize == null)
                {
                    return 50; // Default value
                }

                return this.pageSize;
            }

            set
            {
                this.shouldSerialize["PageSize"] = true;
                hasPropertySetterCalledFor["PageSize"] = true;
                this.pageSize = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CardGroupReq : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPage()
        {
            this.shouldSerialize["Page"] = false;
            this.hasPropertySetterCalledFor["Page"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPageSize()
        {
            this.shouldSerialize["PageSize"] = false;
            this.hasPropertySetterCalledFor["PageSize"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePage()
        {
            return this.shouldSerialize["Page"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePageSize()
        {
            return this.shouldSerialize["PageSize"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CardGroupReq other &&
                (this.Filters == null && other.Filters == null ||
                 this.Filters?.Equals(other.Filters) == true) &&
                (this.Page == null && other.Page == null ||
                 this.Page?.Equals(other.Page) == true) &&
                (this.PageSize == null && other.PageSize == null ||
                 this.PageSize?.Equals(other.PageSize) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Filters = {(this.Filters == null ? "null" : this.Filters.ToString())}");
            toStringOutput.Add($"Page = {(this.Page == null ? "null" : this.Page.ToString())}");
            toStringOutput.Add($"PageSize = {(this.PageSize == null ? "null" : this.PageSize.ToString())}");
        }
    }
}