// <copyright file="CartTypeAccount.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// CartTypeAccount.
    /// </summary>
    public class CartTypeAccount
    {
        private int? accountId;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "AccountId", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="CartTypeAccount"/> class.
        /// </summary>
        public CartTypeAccount()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CartTypeAccount"/> class.
        /// </summary>
        /// <param name="accountId">AccountId.</param>
        /// <param name="accountNumber">AccountNumber.</param>
        /// <param name="isDefault">IsDefault.</param>
        /// <param name="customerCardTypeId">CustomerCardTypeId.</param>
        /// <param name="isVisibleToCustomers">IsVisibleToCustomers.</param>
        /// <param name="embossAccountName">EmbossAccountName.</param>
        /// <param name="defaultPurchaseCategoryId">DefaultPurchaseCategoryId.</param>
        /// <param name="usageRestrictions">UsageRestrictions.</param>
        /// <param name="dayTimeRestrictions">DayTimeRestrictions.</param>
        public CartTypeAccount(
            int? accountId = null,
            string accountNumber = null,
            bool? isDefault = null,
            int? customerCardTypeId = null,
            bool? isVisibleToCustomers = null,
            string embossAccountName = null,
            int? defaultPurchaseCategoryId = null,
            Models.CardUsageRestrictions usageRestrictions = null,
            Models.CardDayTimeRestrictions dayTimeRestrictions = null)
        {

            if (accountId != null)
            {
                this.AccountId = accountId;
            }
            this.AccountNumber = accountNumber;
            this.IsDefault = isDefault;
            this.CustomerCardTypeId = customerCardTypeId;
            this.IsVisibleToCustomers = isVisibleToCustomers;
            this.EmbossAccountName = embossAccountName;
            this.DefaultPurchaseCategoryId = defaultPurchaseCategoryId;
            this.UsageRestrictions = usageRestrictions;
            this.DayTimeRestrictions = dayTimeRestrictions;
        }

        /// <summary>
        /// Account Id of the customer.
        /// </summary>
        [JsonProperty("AccountId")]
        public int? AccountId
        {
            get
            {
                return this.accountId;
            }

            set
            {
                this.shouldSerialize["AccountId"] = true;
                this.accountId = value;
            }
        }

        /// <summary>
        /// Account Number of the customer.
        /// </summary>
        [JsonProperty("AccountNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountNumber { get; set; }

        /// <summary>
        /// Whether card type is default or not.
        /// </summary>
        [JsonProperty("IsDefault", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsDefault { get; set; }

        /// <summary>
        /// Customer Card Type Id in Cards Platform.
        /// </summary>
        [JsonProperty("CustomerCardTypeId", NullValueHandling = NullValueHandling.Ignore)]
        public int? CustomerCardTypeId { get; set; }

        /// <summary>
        /// <![CDATA[
        /// True/False – Whether the card type can be used for card ordering. <br><br> Note - IsVisibleToCustomers will be set as ‘false’ when the card type is not active or. configured in MS to be not visible.
        /// ]]>
        /// </summary>
        [JsonProperty("IsVisibleToCustomers", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsVisibleToCustomers { get; set; }

        /// <summary>
        /// Default Name to be embossed on the card.
        /// </summary>
        [JsonProperty("EmbossAccountName", NullValueHandling = NullValueHandling.Ignore)]
        public string EmbossAccountName { get; set; }

        /// <summary>
        /// Default Purchase category of the card type.
        /// </summary>
        [JsonProperty("DefaultPurchaseCategoryId", NullValueHandling = NullValueHandling.Ignore)]
        public int? DefaultPurchaseCategoryId { get; set; }

        /// <summary>
        /// Gets or sets UsageRestrictions.
        /// </summary>
        [JsonProperty("UsageRestrictions", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CardUsageRestrictions UsageRestrictions { get; set; }

        /// <summary>
        /// Gets or sets DayTimeRestrictions.
        /// </summary>
        [JsonProperty("DayTimeRestrictions", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CardDayTimeRestrictions DayTimeRestrictions { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CartTypeAccount : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccountId()
        {
            this.shouldSerialize["AccountId"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccountId()
        {
            return this.shouldSerialize["AccountId"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CartTypeAccount other &&
                (this.AccountId == null && other.AccountId == null ||
                 this.AccountId?.Equals(other.AccountId) == true) &&
                (this.AccountNumber == null && other.AccountNumber == null ||
                 this.AccountNumber?.Equals(other.AccountNumber) == true) &&
                (this.IsDefault == null && other.IsDefault == null ||
                 this.IsDefault?.Equals(other.IsDefault) == true) &&
                (this.CustomerCardTypeId == null && other.CustomerCardTypeId == null ||
                 this.CustomerCardTypeId?.Equals(other.CustomerCardTypeId) == true) &&
                (this.IsVisibleToCustomers == null && other.IsVisibleToCustomers == null ||
                 this.IsVisibleToCustomers?.Equals(other.IsVisibleToCustomers) == true) &&
                (this.EmbossAccountName == null && other.EmbossAccountName == null ||
                 this.EmbossAccountName?.Equals(other.EmbossAccountName) == true) &&
                (this.DefaultPurchaseCategoryId == null && other.DefaultPurchaseCategoryId == null ||
                 this.DefaultPurchaseCategoryId?.Equals(other.DefaultPurchaseCategoryId) == true) &&
                (this.UsageRestrictions == null && other.UsageRestrictions == null ||
                 this.UsageRestrictions?.Equals(other.UsageRestrictions) == true) &&
                (this.DayTimeRestrictions == null && other.DayTimeRestrictions == null ||
                 this.DayTimeRestrictions?.Equals(other.DayTimeRestrictions) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountId = {(this.AccountId == null ? "null" : this.AccountId.ToString())}");
            toStringOutput.Add($"AccountNumber = {this.AccountNumber ?? "null"}");
            toStringOutput.Add($"IsDefault = {(this.IsDefault == null ? "null" : this.IsDefault.ToString())}");
            toStringOutput.Add($"CustomerCardTypeId = {(this.CustomerCardTypeId == null ? "null" : this.CustomerCardTypeId.ToString())}");
            toStringOutput.Add($"IsVisibleToCustomers = {(this.IsVisibleToCustomers == null ? "null" : this.IsVisibleToCustomers.ToString())}");
            toStringOutput.Add($"EmbossAccountName = {this.EmbossAccountName ?? "null"}");
            toStringOutput.Add($"DefaultPurchaseCategoryId = {(this.DefaultPurchaseCategoryId == null ? "null" : this.DefaultPurchaseCategoryId.ToString())}");
            toStringOutput.Add($"UsageRestrictions = {(this.UsageRestrictions == null ? "null" : this.UsageRestrictions.ToString())}");
            toStringOutput.Add($"DayTimeRestrictions = {(this.DayTimeRestrictions == null ? "null" : this.DayTimeRestrictions.ToString())}");
        }
    }
}