// <copyright file="CustomerPriceListResponse.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// CustomerPriceListResponse.
    /// </summary>
    public class CustomerPriceListResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerPriceListResponse"/> class.
        /// </summary>
        public CustomerPriceListResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerPriceListResponse"/> class.
        /// </summary>
        /// <param name="priceList">PriceList.</param>
        public CustomerPriceListResponse(
            List<Models.PriceList> priceList = null)
        {
            this.PriceList = priceList;
        }

        /// <summary>
        /// Gets or sets PriceList.
        /// </summary>
        [JsonProperty("PriceList", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.PriceList> PriceList { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CustomerPriceListResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CustomerPriceListResponse other &&
                (this.PriceList == null && other.PriceList == null ||
                 this.PriceList?.Equals(other.PriceList) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"PriceList = {(this.PriceList == null ? "null" : $"[{string.Join(", ", this.PriceList)} ]")}");
        }
    }
}