// <copyright file="ExceptionSiteLocation.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// ExceptionSiteLocation.
    /// </summary>
    public class ExceptionSiteLocation
    {
        private string lat;
        private string lng;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "Lat", false },
            { "Lng", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ExceptionSiteLocation"/> class.
        /// </summary>
        public ExceptionSiteLocation()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExceptionSiteLocation"/> class.
        /// </summary>
        /// <param name="lat">Lat.</param>
        /// <param name="lng">Lng.</param>
        public ExceptionSiteLocation(
            string lat = null,
            string lng = null)
        {

            if (lat != null)
            {
                this.Lat = lat;
            }

            if (lng != null)
            {
                this.Lng = lng;
            }
        }

        /// <summary>
        /// Latitude for the Site Geographic Location
        /// </summary>
        [JsonProperty("Lat")]
        public string Lat
        {
            get
            {
                return this.lat;
            }

            set
            {
                this.shouldSerialize["Lat"] = true;
                this.lat = value;
            }
        }

        /// <summary>
        /// Longitude for the Site Geographic Location
        /// </summary>
        [JsonProperty("Lng")]
        public string Lng
        {
            get
            {
                return this.lng;
            }

            set
            {
                this.shouldSerialize["Lng"] = true;
                this.lng = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ExceptionSiteLocation : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetLat()
        {
            this.shouldSerialize["Lat"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetLng()
        {
            this.shouldSerialize["Lng"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeLat()
        {
            return this.shouldSerialize["Lat"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeLng()
        {
            return this.shouldSerialize["Lng"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ExceptionSiteLocation other &&
                (this.Lat == null && other.Lat == null ||
                 this.Lat?.Equals(other.Lat) == true) &&
                (this.Lng == null && other.Lng == null ||
                 this.Lng?.Equals(other.Lng) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Lat = {this.Lat ?? "null"}");
            toStringOutput.Add($"Lng = {this.Lng ?? "null"}");
        }
    }
}