// <copyright file="FuelConsumptionRequest.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// FuelConsumptionRequest.
    /// </summary>
    public class FuelConsumptionRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FuelConsumptionRequest"/> class.
        /// </summary>
        public FuelConsumptionRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FuelConsumptionRequest"/> class.
        /// </summary>
        /// <param name="colCoId">ColCoId.</param>
        /// <param name="colCoCode">ColCoCode.</param>
        /// <param name="payerId">PayerId.</param>
        /// <param name="payerNumber">PayerNumber.</param>
        /// <param name="accounts">Accounts.</param>
        /// <param name="cardGroupId">CardGroupId.</param>
        /// <param name="cardGroupName">CardGroupName.</param>
        /// <param name="cards">Cards.</param>
        /// <param name="fromDate">FromDate.</param>
        /// <param name="toDate">ToDate.</param>
        /// <param name="period">Period.</param>
        public FuelConsumptionRequest(
            int? colCoId = null,
            int? colCoCode = null,
            int? payerId = null,
            string payerNumber = null,
            List<Models.Accounts> accounts = null,
            int? cardGroupId = null,
            string cardGroupName = null,
            List<Models.FuelConsumptionCard> cards = null,
            string fromDate = null,
            string toDate = null,
            int? period = null)
        {
            this.ColCoId = colCoId;
            this.ColCoCode = colCoCode;
            this.PayerId = payerId;
            this.PayerNumber = payerNumber;
            this.Accounts = accounts;
            this.CardGroupId = cardGroupId;
            this.CardGroupName = cardGroupName;
            this.Cards = cards;
            this.FromDate = fromDate;
            this.ToDate = toDate;
            this.Period = period;
        }

        /// <summary>
        /// Collecting Company Id  of the selected payer.
        /// Optional if ColCoCode is passed else Mandatory.
        /// Example:
        /// 1 for Philippines
        /// 5 for UK
        /// </summary>
        [JsonProperty("ColCoId", NullValueHandling = NullValueHandling.Ignore)]
        public int? ColCoId { get; set; }

        /// <summary>
        /// Collecting Company Code  of the selected payer.
        /// Mandatory for serviced OUs such as Romania, Latvia, Lithuania, Estonia, Ukraine etc. It is optional for other countries if ColCoID is provided.
        /// Example:
        /// 86 for Philippines
        /// 5 for UK
        /// </summary>
        [JsonProperty("ColCoCode", NullValueHandling = NullValueHandling.Ignore)]
        public int? ColCoCode { get; set; }

        /// <summary>
        /// Payer Id  of the selected payer.
        /// Optional if PayerNumber is passed else Mandatory
        /// </summary>
        [JsonProperty("PayerId", NullValueHandling = NullValueHandling.Ignore)]
        public int? PayerId { get; set; }

        /// <summary>
        /// Payer Number of the selected payer.
        /// Optional if PayerId is passed else Mandatory
        /// </summary>
        [JsonProperty("PayerNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string PayerNumber { get; set; }

        /// <summary>
        /// Gets or sets Accounts.
        /// </summary>
        [JsonProperty("Accounts", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Accounts> Accounts { get; set; }

        /// <summary>
        /// Card Group Id in GFN
        /// Optional
        /// Example: 200
        /// </summary>
        [JsonProperty("CardGroupId", NullValueHandling = NullValueHandling.Ignore)]
        public int? CardGroupId { get; set; }

        /// <summary>
        /// Card Group Name
        /// Optional
        /// This input is a search criterion, if given.
        /// </summary>
        [JsonProperty("CardGroupName", NullValueHandling = NullValueHandling.Ignore)]
        public string CardGroupName { get; set; }

        /// <summary>
        /// Gets or sets Cards.
        /// </summary>
        [JsonProperty("Cards", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.FuelConsumptionCard> Cards { get; set; }

        /// <summary>
        /// Transactions from Date
        /// Optional – ‘Period’ will be considered when this field is not provided.
        /// </summary>
        [JsonProperty("FromDate", NullValueHandling = NullValueHandling.Ignore)]
        public string FromDate { get; set; }

        /// <summary>
        /// Transactions to Date
        /// Optional
        /// Format: yyyyMMdd
        /// </summary>
        [JsonProperty("ToDate", NullValueHandling = NullValueHandling.Ignore)]
        public string ToDate { get; set; }

        /// <summary>
        /// Transactions Period. This is ignored when FromDate is supplied on the request
        /// Allowed values :
        /// 1.    Last 7 Days
        /// 2.    Last 30 Days
        /// 3.    Last 90 Days
        /// Optional - When FromDate/ToDate and Period are not provided, ‘Last 7 Days’ value is considered as default Period.
        /// </summary>
        [JsonProperty("Period", NullValueHandling = NullValueHandling.Ignore)]
        public int? Period { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"FuelConsumptionRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is FuelConsumptionRequest other &&
                (this.ColCoId == null && other.ColCoId == null ||
                 this.ColCoId?.Equals(other.ColCoId) == true) &&
                (this.ColCoCode == null && other.ColCoCode == null ||
                 this.ColCoCode?.Equals(other.ColCoCode) == true) &&
                (this.PayerId == null && other.PayerId == null ||
                 this.PayerId?.Equals(other.PayerId) == true) &&
                (this.PayerNumber == null && other.PayerNumber == null ||
                 this.PayerNumber?.Equals(other.PayerNumber) == true) &&
                (this.Accounts == null && other.Accounts == null ||
                 this.Accounts?.Equals(other.Accounts) == true) &&
                (this.CardGroupId == null && other.CardGroupId == null ||
                 this.CardGroupId?.Equals(other.CardGroupId) == true) &&
                (this.CardGroupName == null && other.CardGroupName == null ||
                 this.CardGroupName?.Equals(other.CardGroupName) == true) &&
                (this.Cards == null && other.Cards == null ||
                 this.Cards?.Equals(other.Cards) == true) &&
                (this.FromDate == null && other.FromDate == null ||
                 this.FromDate?.Equals(other.FromDate) == true) &&
                (this.ToDate == null && other.ToDate == null ||
                 this.ToDate?.Equals(other.ToDate) == true) &&
                (this.Period == null && other.Period == null ||
                 this.Period?.Equals(other.Period) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ColCoId = {(this.ColCoId == null ? "null" : this.ColCoId.ToString())}");
            toStringOutput.Add($"ColCoCode = {(this.ColCoCode == null ? "null" : this.ColCoCode.ToString())}");
            toStringOutput.Add($"PayerId = {(this.PayerId == null ? "null" : this.PayerId.ToString())}");
            toStringOutput.Add($"PayerNumber = {this.PayerNumber ?? "null"}");
            toStringOutput.Add($"Accounts = {(this.Accounts == null ? "null" : $"[{string.Join(", ", this.Accounts)} ]")}");
            toStringOutput.Add($"CardGroupId = {(this.CardGroupId == null ? "null" : this.CardGroupId.ToString())}");
            toStringOutput.Add($"CardGroupName = {this.CardGroupName ?? "null"}");
            toStringOutput.Add($"Cards = {(this.Cards == null ? "null" : $"[{string.Join(", ", this.Cards)} ]")}");
            toStringOutput.Add($"FromDate = {this.FromDate ?? "null"}");
            toStringOutput.Add($"ToDate = {this.ToDate ?? "null"}");
            toStringOutput.Add($"Period = {(this.Period == null ? "null" : this.Period.ToString())}");
        }
    }
}