// <copyright file="LoggedInUserReq.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// LoggedInUserReq.
    /// </summary>
    public class LoggedInUserReq
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LoggedInUserReq"/> class.
        /// </summary>
        public LoggedInUserReq()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoggedInUserReq"/> class.
        /// </summary>
        /// <param name="filters">Filters.</param>
        public LoggedInUserReq(
            Models.FleetmanagementV1UserLoggedinuserRequest filters = null)
        {
            this.Filters = filters;
        }

        /// <summary>
        /// Gets or sets Filters.
        /// </summary>
        [JsonProperty("Filters", NullValueHandling = NullValueHandling.Ignore)]
        public Models.FleetmanagementV1UserLoggedinuserRequest Filters { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"LoggedInUserReq : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is LoggedInUserReq other &&
                (this.Filters == null && other.Filters == null ||
                 this.Filters?.Equals(other.Filters) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Filters = {(this.Filters == null ? "null" : this.Filters.ToString())}");
        }
    }
}