// <copyright file="MultiPricedTransactionResponse.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// MultiPricedTransactionResponse.
    /// </summary>
    public class MultiPricedTransactionResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultiPricedTransactionResponse"/> class.
        /// </summary>
        public MultiPricedTransactionResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MultiPricedTransactionResponse"/> class.
        /// </summary>
        /// <param name="transactions">Transactions.</param>
        public MultiPricedTransactionResponse(
            List<Models.MultiPricedTransactionResponseTransactionsItems> transactions = null)
        {
            this.Transactions = transactions;
        }

        /// <summary>
        /// Gets or sets Transactions.
        /// </summary>
        [JsonProperty("Transactions", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.MultiPricedTransactionResponseTransactionsItems> Transactions { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"MultiPricedTransactionResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is MultiPricedTransactionResponse other &&
                (this.Transactions == null && other.Transactions == null ||
                 this.Transactions?.Equals(other.Transactions) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Transactions = {(this.Transactions == null ? "null" : $"[{string.Join(", ", this.Transactions)} ]")}");
        }
    }
}