// <copyright file="PayerRes.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ShellDataReportingAPIs.Standard;
using ShellDataReportingAPIs.Standard.Utilities;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// PayerRes.
    /// </summary>
    public class PayerRes
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayerRes"/> class.
        /// </summary>
        public PayerRes()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PayerRes"/> class.
        /// </summary>
        /// <param name="requestId">RequestId.</param>
        /// <param name="status">Status.</param>
        /// <param name="data">Data.</param>
        /// <param name="page">Page.</param>
        /// <param name="totalRecords">TotalRecords.</param>
        /// <param name="totalPages">TotalPages.</param>
        /// <param name="pageSize">PageSize.</param>
        /// <param name="warnings">Warnings.</param>
        public PayerRes(
            string requestId = null,
            string status = null,
            List<Models.PayerDetails> data = null,
            int? page = null,
            int? totalRecords = null,
            int? totalPages = null,
            int? pageSize = null,
            List<Models.Warning> warnings = null)
        {
            this.RequestId = requestId;
            this.Status = status;
            this.Data = data;
            this.Page = page;
            this.TotalRecords = totalRecords;
            this.TotalPages = totalPages;
            this.PageSize = pageSize;
            this.Warnings = warnings;
        }

        /// <summary>
        /// Unique identifier for the request. This will be played back in the response from the request.
        /// </summary>
        [JsonProperty("RequestId", NullValueHandling = NullValueHandling.Ignore)]
        public string RequestId { get; set; }

        /// <summary>
        /// Status of the request
        /// </summary>
        [JsonProperty("Status", NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets Data.
        /// </summary>
        [JsonProperty("Data", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.PayerDetails> Data { get; set; }

        /// <summary>
        /// Current Page
        /// </summary>
        [JsonProperty("Page", NullValueHandling = NullValueHandling.Ignore)]
        public int? Page { get; set; }

        /// <summary>
        /// Total row count matched for the given input criteria
        /// </summary>
        [JsonProperty("TotalRecords", NullValueHandling = NullValueHandling.Ignore)]
        public int? TotalRecords { get; set; }

        /// <summary>
        /// Calculated page count based on page size from the incoming API request and total number of rows matched for the given input criteria. Return 1 if the page size is -1 as all records are returned.
        /// </summary>
        [JsonProperty("TotalPages", NullValueHandling = NullValueHandling.Ignore)]
        public int? TotalPages { get; set; }

        /// <summary>
        /// Page Size – Number of records to show on current page.
        /// </summary>
        [JsonProperty("PageSize", NullValueHandling = NullValueHandling.Ignore)]
        public int? PageSize { get; set; }

        /// <summary>
        /// A list of Warning entity.
        /// This entity will hold the details of the scheduled System Outages of any dependent applications of this service.
        /// Note: If there is no scheduled outage information available, in the configuration in AMS, for this service, this parameter won’t be present in output.
        /// </summary>
        [JsonProperty("Warnings", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Warning> Warnings { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PayerRes : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PayerRes other &&
                (this.RequestId == null && other.RequestId == null ||
                 this.RequestId?.Equals(other.RequestId) == true) &&
                (this.Status == null && other.Status == null ||
                 this.Status?.Equals(other.Status) == true) &&
                (this.Data == null && other.Data == null ||
                 this.Data?.Equals(other.Data) == true) &&
                (this.Page == null && other.Page == null ||
                 this.Page?.Equals(other.Page) == true) &&
                (this.TotalRecords == null && other.TotalRecords == null ||
                 this.TotalRecords?.Equals(other.TotalRecords) == true) &&
                (this.TotalPages == null && other.TotalPages == null ||
                 this.TotalPages?.Equals(other.TotalPages) == true) &&
                (this.PageSize == null && other.PageSize == null ||
                 this.PageSize?.Equals(other.PageSize) == true) &&
                (this.Warnings == null && other.Warnings == null ||
                 this.Warnings?.Equals(other.Warnings) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"RequestId = {this.RequestId ?? "null"}");
            toStringOutput.Add($"Status = {this.Status ?? "null"}");
            toStringOutput.Add($"Data = {(this.Data == null ? "null" : $"[{string.Join(", ", this.Data)} ]")}");
            toStringOutput.Add($"Page = {(this.Page == null ? "null" : this.Page.ToString())}");
            toStringOutput.Add($"TotalRecords = {(this.TotalRecords == null ? "null" : this.TotalRecords.ToString())}");
            toStringOutput.Add($"TotalPages = {(this.TotalPages == null ? "null" : this.TotalPages.ToString())}");
            toStringOutput.Add($"PageSize = {(this.PageSize == null ? "null" : this.PageSize.ToString())}");
            toStringOutput.Add($"Warnings = {(this.Warnings == null ? "null" : $"[{string.Join(", ", this.Warnings)} ]")}");
        }
    }
}