// <copyright file="PayerRequest.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ShellDataReportingAPIs.Standard;
using ShellDataReportingAPIs.Standard.Utilities;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// PayerRequest.
    /// </summary>
    public class PayerRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayerRequest"/> class.
        /// </summary>
        public PayerRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PayerRequest"/> class.
        /// </summary>
        /// <param name="payers">Payers.</param>
        /// <param name="returnBasicDetailsOnly">ReturnBasicDetailsOnly.</param>
        /// <param name="includeAddresses">IncludeAddresses.</param>
        /// <param name="includeBonusParameters">IncludeBonusParameters.</param>
        public PayerRequest(
            List<Models.Payers> payers = null,
            bool? returnBasicDetailsOnly = false,
            bool? includeAddresses = false,
            bool? includeBonusParameters = false)
        {
            this.Payers = payers;
            this.ReturnBasicDetailsOnly = returnBasicDetailsOnly;
            this.IncludeAddresses = includeAddresses;
            this.IncludeBonusParameters = includeBonusParameters;
        }

        /// <summary>
        /// List of Payer entity.
        /// Optional.
        /// Note:
        /// •    Max number of payers allowed in the input is 10, if it exceeds in the input it will throw an error.
        /// •    This value is configurable. Initial configuration will be 1000 and will change to 10 once SFH changes are integrated.
        /// </summary>
        [JsonProperty("Payers", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Payers> Payers { get; set; }

        /// <summary>
        /// Returns only the high-level basic details of payers. Set this field to ‘true’ when only the basic details are required to get the result quicker.
        /// </summary>
        [JsonProperty("ReturnBasicDetailsOnly", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ReturnBasicDetailsOnly { get; set; }

        /// <summary>
        /// Include address related fields on the response. Set this field to ‘False’ when Address fields are not required to get the result quicker.
        /// </summary>
        [JsonProperty("IncludeAddresses", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IncludeAddresses { get; set; }

        /// <summary>
        /// Include the Finance Currency, used for Finance Widget, in the response
        /// </summary>
        [JsonProperty("IncludeBonusParameters", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IncludeBonusParameters { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PayerRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PayerRequest other &&
                (this.Payers == null && other.Payers == null ||
                 this.Payers?.Equals(other.Payers) == true) &&
                (this.ReturnBasicDetailsOnly == null && other.ReturnBasicDetailsOnly == null ||
                 this.ReturnBasicDetailsOnly?.Equals(other.ReturnBasicDetailsOnly) == true) &&
                (this.IncludeAddresses == null && other.IncludeAddresses == null ||
                 this.IncludeAddresses?.Equals(other.IncludeAddresses) == true) &&
                (this.IncludeBonusParameters == null && other.IncludeBonusParameters == null ||
                 this.IncludeBonusParameters?.Equals(other.IncludeBonusParameters) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Payers = {(this.Payers == null ? "null" : $"[{string.Join(", ", this.Payers)} ]")}");
            toStringOutput.Add($"ReturnBasicDetailsOnly = {(this.ReturnBasicDetailsOnly == null ? "null" : this.ReturnBasicDetailsOnly.ToString())}");
            toStringOutput.Add($"IncludeAddresses = {(this.IncludeAddresses == null ? "null" : this.IncludeAddresses.ToString())}");
            toStringOutput.Add($"IncludeBonusParameters = {(this.IncludeBonusParameters == null ? "null" : this.IncludeBonusParameters.ToString())}");
        }
    }
}