// <copyright file="PricedTransactionReqV2PeriodEnum.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// PricedTransactionReqV2PeriodEnum.
    /// </summary>

    [JsonConverter(typeof(NumberEnumConverter))]
    public enum PricedTransactionReqV2PeriodEnum
    {
        /// <summary>
        /// Enum1.
        /// </summary>
        Enum1 = 1,

        /// <summary>
        /// Enum2.
        /// </summary>
        Enum2 = 2,

        /// <summary>
        /// Enum3.
        /// </summary>
        Enum3 = 3
    }
}