// <copyright file="PriceTransSummaryReq.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ShellDataReportingAPIs.Standard;
using ShellDataReportingAPIs.Standard.Utilities;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// PriceTransSummaryReq.
    /// </summary>
    public class PriceTransSummaryReq
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PriceTransSummaryReq"/> class.
        /// </summary>
        public PriceTransSummaryReq()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PriceTransSummaryReq"/> class.
        /// </summary>
        /// <param name="filters">Filters.</param>
        public PriceTransSummaryReq(
            Models.PriceTransSummaryRequest filters = null)
        {
            this.Filters = filters;
        }

        /// <summary>
        /// Gets or sets Filters.
        /// </summary>
        [JsonProperty("Filters", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PriceTransSummaryRequest Filters { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PriceTransSummaryReq : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PriceTransSummaryReq other &&
                (this.Filters == null && other.Filters == null ||
                 this.Filters?.Equals(other.Filters) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Filters = {(this.Filters == null ? "null" : this.Filters.ToString())}");
        }
    }
}