// <copyright file="PricedTransactionReqV2SortOrderEnum.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// PricedTransactionReqV2SortOrderEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum PricedTransactionReqV2SortOrderEnum
    {
        /// <summary>
        /// Enum1.
        /// </summary>
        [EnumMember(Value = "1")]
        Enum1,

        /// <summary>
        /// Enum2.
        /// </summary>
        [EnumMember(Value = "2")]
        Enum2,

        /// <summary>
        /// Enum3.
        /// </summary>
        [EnumMember(Value = "3")]
        Enum3,

        /// <summary>
        /// Enum4.
        /// </summary>
        [EnumMember(Value = "4")]
        Enum4,

        /// <summary>
        /// Enum5.
        /// </summary>
        [EnumMember(Value = "5")]
        Enum5,

        /// <summary>
        /// Enum6.
        /// </summary>
        [EnumMember(Value = "6")]
        Enum6
    }
}