// <copyright file="PricedTransactionItemsLocationItems.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// PricedTransactionItemsLocationItems.
    /// </summary>
    public class PricedTransactionItemsLocationItems
    {
        private string latitude;
        private string longitude;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "Latitude", false },
            { "Longitude", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="PricedTransactionItemsLocationItems"/> class.
        /// </summary>
        public PricedTransactionItemsLocationItems()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PricedTransactionItemsLocationItems"/> class.
        /// </summary>
        /// <param name="latitude">Latitude.</param>
        /// <param name="longitude">Longitude.</param>
        public PricedTransactionItemsLocationItems(
            string latitude = null,
            string longitude = null)
        {

            if (latitude != null)
            {
                this.Latitude = latitude;
            }

            if (longitude != null)
            {
                this.Longitude = longitude;
            }
        }

        /// <summary>
        /// Latitude for the Site Geographic Location
        /// Example: 37.4224764
        /// Note: - The value could be null/blank for fees item.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("Latitude")]
        public string Latitude
        {
            get
            {
                return this.latitude;
            }

            set
            {
                this.shouldSerialize["Latitude"] = true;
                this.latitude = value;
            }
        }

        /// <summary>
        /// Longitude for the Site Geographic Location
        /// Example: 122.0842499
        /// Note: - The value could be null/blank for fees item.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("Longitude")]
        public string Longitude
        {
            get
            {
                return this.longitude;
            }

            set
            {
                this.shouldSerialize["Longitude"] = true;
                this.longitude = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PricedTransactionItemsLocationItems : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetLatitude()
        {
            this.shouldSerialize["Latitude"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetLongitude()
        {
            this.shouldSerialize["Longitude"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeLatitude()
        {
            return this.shouldSerialize["Latitude"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeLongitude()
        {
            return this.shouldSerialize["Longitude"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PricedTransactionItemsLocationItems other &&
                (this.Latitude == null && other.Latitude == null ||
                 this.Latitude?.Equals(other.Latitude) == true) &&
                (this.Longitude == null && other.Longitude == null ||
                 this.Longitude?.Equals(other.Longitude) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Latitude = {this.Latitude ?? "null"}");
            toStringOutput.Add($"Longitude = {this.Longitude ?? "null"}");
        }
    }
}