// <copyright file="TransactionExceptionsResponse.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// TransactionExceptionsResponse.
    /// </summary>
    public class TransactionExceptionsResponse
    {
        private List<Models.TransactionExceptions> transactionExceptions;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "TransactionExceptions", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionExceptionsResponse"/> class.
        /// </summary>
        public TransactionExceptionsResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionExceptionsResponse"/> class.
        /// </summary>
        /// <param name="cardExceptions">CardExceptions.</param>
        /// <param name="transactionExceptions">TransactionExceptions.</param>
        public TransactionExceptionsResponse(
            List<Models.CardExceptions> cardExceptions = null,
            List<Models.TransactionExceptions> transactionExceptions = null)
        {
            this.CardExceptions = cardExceptions;

            if (transactionExceptions != null)
            {
                this.TransactionExceptions = transactionExceptions;
            }
        }

        /// <summary>
        /// Gets or sets CardExceptions.
        /// </summary>
        [JsonProperty("CardExceptions", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.CardExceptions> CardExceptions { get; set; }

        /// <summary>
        /// Gets or sets TransactionExceptions.
        /// </summary>
        [JsonProperty("TransactionExceptions")]
        public List<Models.TransactionExceptions> TransactionExceptions
        {
            get
            {
                return this.transactionExceptions;
            }

            set
            {
                this.shouldSerialize["TransactionExceptions"] = true;
                this.transactionExceptions = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TransactionExceptionsResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTransactionExceptions()
        {
            this.shouldSerialize["TransactionExceptions"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTransactionExceptions()
        {
            return this.shouldSerialize["TransactionExceptions"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is TransactionExceptionsResponse other &&
                (this.CardExceptions == null && other.CardExceptions == null ||
                 this.CardExceptions?.Equals(other.CardExceptions) == true) &&
                (this.TransactionExceptions == null && other.TransactionExceptions == null ||
                 this.TransactionExceptions?.Equals(other.TransactionExceptions) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CardExceptions = {(this.CardExceptions == null ? "null" : $"[{string.Join(", ", this.CardExceptions)} ]")}");
            toStringOutput.Add($"TransactionExceptions = {(this.TransactionExceptions == null ? "null" : $"[{string.Join(", ", this.TransactionExceptions)} ]")}");
        }
    }
}