// <copyright file="UpdateOdometerResponse.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ShellDataReportingAPIs.Standard;
using ShellDataReportingAPIs.Standard.Utilities;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// UpdateOdometerResponse.
    /// </summary>
    public class UpdateOdometerResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateOdometerResponse"/> class.
        /// </summary>
        public UpdateOdometerResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateOdometerResponse"/> class.
        /// </summary>
        /// <param name="serviceReference">ServiceReference.</param>
        /// <param name="updateOdometerReferences">UpdateOdometerReferences.</param>
        public UpdateOdometerResponse(
            int? serviceReference = null,
            List<Models.UpdateOdometerReference> updateOdometerReferences = null)
        {
            this.ServiceReference = serviceReference;
            this.UpdateOdometerReferences = updateOdometerReferences;
        }

        /// <summary>
        /// Main reference number for tracking.
        /// </summary>
        [JsonProperty("ServiceReference", NullValueHandling = NullValueHandling.Ignore)]
        public int? ServiceReference { get; set; }

        /// <summary>
        /// Gets or sets UpdateOdometerReferences.
        /// </summary>
        [JsonProperty("UpdateOdometerReferences", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.UpdateOdometerReference> UpdateOdometerReferences { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"UpdateOdometerResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is UpdateOdometerResponse other &&
                (this.ServiceReference == null && other.ServiceReference == null ||
                 this.ServiceReference?.Equals(other.ServiceReference) == true) &&
                (this.UpdateOdometerReferences == null && other.UpdateOdometerReferences == null ||
                 this.UpdateOdometerReferences?.Equals(other.UpdateOdometerReferences) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ServiceReference = {(this.ServiceReference == null ? "null" : this.ServiceReference.ToString())}");
            toStringOutput.Add($"UpdateOdometerReferences = {(this.UpdateOdometerReferences == null ? "null" : $"[{string.Join(", ", this.UpdateOdometerReferences)} ]")}");
        }
    }
}