// <copyright file="UpdateOdometer.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// UpdateOdometer.
    /// </summary>
    public class UpdateOdometer
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateOdometer"/> class.
        /// </summary>
        public UpdateOdometer()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateOdometer"/> class.
        /// </summary>
        /// <param name="salesItemId">SalesItemId.</param>
        /// <param name="newOdometerValue">NewOdometerValue.</param>
        public UpdateOdometer(
            string salesItemId = null,
            int? newOdometerValue = null)
        {
            this.SalesItemId = salesItemId;
            this.NewOdometerValue = newOdometerValue;
        }

        /// <summary>
        /// Unique SalesItemId (Either Billed on Unbilled)
        /// Mandatory
        /// </summary>
        [JsonProperty("SalesItemId", NullValueHandling = NullValueHandling.Include)]
        public string SalesItemId { get; set; }

        /// <summary>
        /// NewOdometerValue that needs to be updated
        /// </summary>
        [JsonProperty("NewOdometerValue", NullValueHandling = NullValueHandling.Include)]
        public int? NewOdometerValue { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"UpdateOdometer : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is UpdateOdometer other &&
                (this.SalesItemId == null && other.SalesItemId == null ||
                 this.SalesItemId?.Equals(other.SalesItemId) == true) &&
                (this.NewOdometerValue == null && other.NewOdometerValue == null ||
                 this.NewOdometerValue?.Equals(other.NewOdometerValue) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"SalesItemId = {this.SalesItemId ?? "null"}");
            toStringOutput.Add($"NewOdometerValue = {(this.NewOdometerValue == null ? "null" : this.NewOdometerValue.ToString())}");
        }
    }
}