// <copyright file="VolumeBasedBonusRes.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// VolumeBasedBonusRes.
    /// </summary>
    public class VolumeBasedBonusRes
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VolumeBasedBonusRes"/> class.
        /// </summary>
        public VolumeBasedBonusRes()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="VolumeBasedBonusRes"/> class.
        /// </summary>
        /// <param name="requestId">RequestId.</param>
        /// <param name="status">Status.</param>
        /// <param name="data">Data.</param>
        /// <param name="warnings">Warnings.</param>
        public VolumeBasedBonusRes(
            string requestId = null,
            string status = null,
            List<Models.VolumeBasedBonusResponse> data = null,
            List<Models.Warning> warnings = null)
        {
            this.RequestId = requestId;
            this.Status = status;
            this.Data = data;
            this.Warnings = warnings;
        }

        /// <summary>
        /// Unique identifier for the request. This will be played back in the response from the request.
        /// </summary>
        [JsonProperty("RequestId", NullValueHandling = NullValueHandling.Ignore)]
        public string RequestId { get; set; }

        /// <summary>
        /// Status of the request
        /// </summary>
        [JsonProperty("Status", NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets Data.
        /// </summary>
        [JsonProperty("Data", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.VolumeBasedBonusResponse> Data { get; set; }

        /// <summary>
        /// A list of Warning entity.
        /// This entity will hold the details of the scheduled System Outages of any dependent applications of this service.
        /// Note: If there is no scheduled outage information available, in the configuration in AMS, for this service, this parameter won’t be present in output.
        /// </summary>
        [JsonProperty("Warnings", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Warning> Warnings { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"VolumeBasedBonusRes : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is VolumeBasedBonusRes other &&
                (this.RequestId == null && other.RequestId == null ||
                 this.RequestId?.Equals(other.RequestId) == true) &&
                (this.Status == null && other.Status == null ||
                 this.Status?.Equals(other.Status) == true) &&
                (this.Data == null && other.Data == null ||
                 this.Data?.Equals(other.Data) == true) &&
                (this.Warnings == null && other.Warnings == null ||
                 this.Warnings?.Equals(other.Warnings) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"RequestId = {this.RequestId ?? "null"}");
            toStringOutput.Add($"Status = {this.Status ?? "null"}");
            toStringOutput.Add($"Data = {(this.Data == null ? "null" : $"[{string.Join(", ", this.Data)} ]")}");
            toStringOutput.Add($"Warnings = {(this.Warnings == null ? "null" : $"[{string.Join(", ", this.Warnings)} ]")}");
        }
    }
}