// <copyright file="VolumeBasedPricingResponse.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ShellDataReportingAPIs.Standard;
using ShellDataReportingAPIs.Standard.Utilities;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// VolumeBasedPricingResponse.
    /// </summary>
    public class VolumeBasedPricingResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VolumeBasedPricingResponse"/> class.
        /// </summary>
        public VolumeBasedPricingResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="VolumeBasedPricingResponse"/> class.
        /// </summary>
        /// <param name="configuration">Configuration.</param>
        /// <param name="currentPeriodConsumption">CurrentPeriodConsumption.</param>
        /// <param name="history">History.</param>
        /// <param name="warnings">Warnings.</param>
        public VolumeBasedPricingResponse(
            List<Models.BonusConfiguration> configuration = null,
            List<Models.PricingCurrentVolume> currentPeriodConsumption = null,
            List<Models.PricingHistory> history = null,
            List<Models.Warning> warnings = null)
        {
            this.Configuration = configuration;
            this.CurrentPeriodConsumption = currentPeriodConsumption;
            this.History = history;
            this.Warnings = warnings;
        }

        /// <summary>
        /// Gets or sets Configuration.
        /// </summary>
        [JsonProperty("Configuration", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.BonusConfiguration> Configuration { get; set; }

        /// <summary>
        /// Gets or sets CurrentPeriodConsumption.
        /// </summary>
        [JsonProperty("CurrentPeriodConsumption", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.PricingCurrentVolume> CurrentPeriodConsumption { get; set; }

        /// <summary>
        /// Gets or sets History.
        /// </summary>
        [JsonProperty("History", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.PricingHistory> History { get; set; }

        /// <summary>
        /// A list of Warning entity.
        /// This entity will hold the details of the scheduled System Outages of any dependent applications of this service.
        /// Note: If there is no scheduled outage information available, in the configuration in AMS, for this service, this parameter won’t be present in output.
        /// </summary>
        [JsonProperty("Warnings", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Warning> Warnings { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"VolumeBasedPricingResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is VolumeBasedPricingResponse other &&
                (this.Configuration == null && other.Configuration == null ||
                 this.Configuration?.Equals(other.Configuration) == true) &&
                (this.CurrentPeriodConsumption == null && other.CurrentPeriodConsumption == null ||
                 this.CurrentPeriodConsumption?.Equals(other.CurrentPeriodConsumption) == true) &&
                (this.History == null && other.History == null ||
                 this.History?.Equals(other.History) == true) &&
                (this.Warnings == null && other.Warnings == null ||
                 this.Warnings?.Equals(other.Warnings) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Configuration = {(this.Configuration == null ? "null" : $"[{string.Join(", ", this.Configuration)} ]")}");
            toStringOutput.Add($"CurrentPeriodConsumption = {(this.CurrentPeriodConsumption == null ? "null" : $"[{string.Join(", ", this.CurrentPeriodConsumption)} ]")}");
            toStringOutput.Add($"History = {(this.History == null ? "null" : $"[{string.Join(", ", this.History)} ]")}");
            toStringOutput.Add($"Warnings = {(this.Warnings == null ? "null" : $"[{string.Join(", ", this.Warnings)} ]")}");
        }
    }
}