// <copyright file="VolumeBasedBonusResponse.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Collections.Generic;

namespace ShellDataReportingAPIs.Standard.Models
{
    /// <summary>
    /// VolumeBasedBonusResponse.
    /// </summary>
    public class VolumeBasedBonusResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VolumeBasedBonusResponse"/> class.
        /// </summary>
        public VolumeBasedBonusResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="VolumeBasedBonusResponse"/> class.
        /// </summary>
        /// <param name="configuration">Configuration.</param>
        /// <param name="currentPeriodConsumption">CurrentPeriodConsumption.</param>
        /// <param name="historicalBonusPaid">HistoricalBonusPaid.</param>
        public VolumeBasedBonusResponse(
            List<Models.BonusConfiguration> configuration = null,
            List<Models.CurrentVolume> currentPeriodConsumption = null,
            List<Models.BonusHistory> historicalBonusPaid = null)
        {
            this.Configuration = configuration;
            this.CurrentPeriodConsumption = currentPeriodConsumption;
            this.HistoricalBonusPaid = historicalBonusPaid;
        }

        /// <summary>
        /// Gets or sets Configuration.
        /// </summary>
        [JsonProperty("Configuration", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.BonusConfiguration> Configuration { get; set; }

        /// <summary>
        /// Gets or sets CurrentPeriodConsumption.
        /// </summary>
        [JsonProperty("CurrentPeriodConsumption", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.CurrentVolume> CurrentPeriodConsumption { get; set; }

        /// <summary>
        /// Gets or sets HistoricalBonusPaid.
        /// </summary>
        [JsonProperty("HistoricalBonusPaid", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.BonusHistory> HistoricalBonusPaid { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"VolumeBasedBonusResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is VolumeBasedBonusResponse other &&
                (this.Configuration == null && other.Configuration == null ||
                 this.Configuration?.Equals(other.Configuration) == true) &&
                (this.CurrentPeriodConsumption == null && other.CurrentPeriodConsumption == null ||
                 this.CurrentPeriodConsumption?.Equals(other.CurrentPeriodConsumption) == true) &&
                (this.HistoricalBonusPaid == null && other.HistoricalBonusPaid == null ||
                 this.HistoricalBonusPaid?.Equals(other.HistoricalBonusPaid) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Configuration = {(this.Configuration == null ? "null" : $"[{string.Join(", ", this.Configuration)} ]")}");
            toStringOutput.Add($"CurrentPeriodConsumption = {(this.CurrentPeriodConsumption == null ? "null" : $"[{string.Join(", ", this.CurrentPeriodConsumption)} ]")}");
            toStringOutput.Add($"HistoricalBonusPaid = {(this.HistoricalBonusPaid == null ? "null" : $"[{string.Join(", ", this.HistoricalBonusPaid)} ]")}");
        }
    }
}