// <copyright file="PricedTransactionResponseTransactionsItemsLocation.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace ShellDataReportingAPIs.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<PricedTransactionResponseTransactionsItemsLocation>),
        new[] {
            typeof(MObjectCase),
            typeof(PricedTransactionItemsLocationItemsCase)
        },
        true
    )]
    public abstract class PricedTransactionResponseTransactionsItemsLocation
    {
        /// <summary>
        /// This is Object case.
        /// </summary>
        /// <returns>
        /// The PricedTransactionResponseTransactionsItemsLocation instance, wrapping the provided object value.
        /// </returns>
        public static PricedTransactionResponseTransactionsItemsLocation FromObject(object mObject)
        {
            return new MObjectCase().Set(mObject);
        }

        /// <summary>
        /// This is PricedTransactionItemsLocationItems case.
        /// </summary>
        /// <returns>
        /// The PricedTransactionResponseTransactionsItemsLocation instance, wrapping the provided PricedTransactionItemsLocationItems value.
        /// </returns>
        public static PricedTransactionResponseTransactionsItemsLocation FromPricedTransactionItemsLocationItems(PricedTransactionItemsLocationItems pricedTransactionItemsLocationItems)
        {
            return new PricedTransactionItemsLocationItemsCase().Set(pricedTransactionItemsLocationItems);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<object, T> mObject, Func<PricedTransactionItemsLocationItems, T> pricedTransactionItemsLocationItems);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<object, T> mObject = null, Func<PricedTransactionItemsLocationItems, T> pricedTransactionItemsLocationItems = null) =>
                Match(mObject, pricedTransactionItemsLocationItems);

        [JsonConverter(typeof(UnionTypeCaseConverter<MObjectCase, object>))]
        private sealed class MObjectCase : PricedTransactionResponseTransactionsItemsLocation, ICaseValue<MObjectCase, object>
        {
            public object Value;

            public override T Match<T>(Func<object, T> mObject, Func<PricedTransactionItemsLocationItems, T> pricedTransactionItemsLocationItems) =>
                   mObject != null ? mObject(Value) : default;

            public MObjectCase Set(object value)
            {
                Value = value;
                return this;
            }

            public object Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is MObjectCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<PricedTransactionItemsLocationItemsCase, PricedTransactionItemsLocationItems>))]
        private sealed class PricedTransactionItemsLocationItemsCase : PricedTransactionResponseTransactionsItemsLocation, ICaseValue<PricedTransactionItemsLocationItemsCase, PricedTransactionItemsLocationItems>
        {
            public PricedTransactionItemsLocationItems Value;

            public override T Match<T>(Func<object, T> mObject, Func<PricedTransactionItemsLocationItems, T> pricedTransactionItemsLocationItems) =>
                   pricedTransactionItemsLocationItems != null ? pricedTransactionItemsLocationItems(Value) : default;

            public PricedTransactionItemsLocationItemsCase Set(PricedTransactionItemsLocationItems value)
            {
                Value = value;
                return this;
            }

            public PricedTransactionItemsLocationItems Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }

            public override bool Equals(object obj)
            {
                if (!(obj is PricedTransactionItemsLocationItemsCase other)) return false;
                if (ReferenceEquals(this, other)) return true;
                return Value == null ? other.Value == null : Value?.Equals(other.Value) == true; 
            }
        }
    }
}