// <copyright file="Server.cs" company="APIMatic">
// ShellDataReportingAPIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>

namespace ShellDataReportingAPIs.Standard
{
    /// <summary>
    /// Available servers.
    /// </summary>
    public enum Server
    {
        /// <summary>
        /// OAuthServer.
        /// </summary>
        OAuthServer,

        /// <summary>
        /// Shell.
        /// </summary>
        Shell,
    }
}
